controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_posts:
    path: /posts
    controller: App\Controller\PostsController::index
    methods: GET

app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET