controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_posts_api:
    path: /posts
    controller: App\Controller\PostsController::show_api
    methods: GET

app_posts_editor:
    path: /lista
    controller: App\Controller\PostsController::show_editor
    methods: GET

app_posts_editor_delete:
    path: /lista
    controller: App\Controller\PostsController::editor_delete
    methods: POST

app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET